### Common user
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe1@email.com",
  "password": "password"
}

### Partner user
POST http://localhost:3000/partner/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoepartner@partner.com",
  "password": "password"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "johndoe1@email.com",
  "password": "password"
}

### Login Partner
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "johndoepartner@partner.com",
  "password": "password"
}


### Create Partner
POST http://localhost:3000/partner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lcGFydG5lckBwYXJ0bmVyLmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNy0yNVQxOToxNTo1OC43NTVaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0yNVQxOToxNTo1OC43NTVaIiwiaWF0IjoxNzIyNDU0Nzc3LCJleHAiOjE3MjI0NjA3Nzd9.29dvm--KhjdHOm3gbG4Xr9YMCPvUdkG4JN0TgAqY968

{
  "name": "Partner 1"
}

### List partners
GET http://localhost:3000/partner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lcGFydG5lckBwYXJ0bmVyLmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNy0yNVQxOToxNTo1OC43NTVaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0yNVQxOToxNTo1OC43NTVaIiwiaWF0IjoxNzIyNDU0Nzc3LCJleHAiOjE3MjI0NjA3Nzd9.29dvm--KhjdHOm3gbG4Xr9YMCPvUdkG4JN0TgAqY968


### Create Event
POST http://localhost:3000/event
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lcGFydG5lckBwYXJ0bmVyLmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNy0yNVQxOToxNTo1OC43NTVaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0yNVQxOToxNTo1OC43NTVaIiwiaWF0IjoxNzIyNDU0Nzc3LCJleHAiOjE3MjI0NjA3Nzd9.29dvm--KhjdHOm3gbG4Xr9YMCPvUdkG4JN0TgAqY968

{
  "name": "Event 2",
  "description": "Nice event 2",
  "date": "2024-09-20T15:15:14.143Z"
}

### List events
GET http://localhost:3000/event
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lcGFydG5lckBwYXJ0bmVyLmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNy0yNVQxOToxNTo1OC43NTVaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0yNVQxOToxNTo1OC43NTVaIiwiaWF0IjoxNzIyNDU0Nzc3LCJleHAiOjE3MjI0NjA3Nzd9.29dvm--KhjdHOm3gbG4Xr9YMCPvUdkG4JN0TgAqY968