services:
  postgres:
    image: postgres:16.3
    restart: on-failure
    ports:
      - '5432:5432'
    # command: "postgres -c max_locks_per_transaction=2048 -c shared_buffers=256MB"
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: nestdocker
      POSTGRES_PASSWORD: nestdocker
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
